CREATE TABLE IF NOT EXISTS weather_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    weather_type VARCHAR(50) NOT NULL DEFAULT 'CLEAR',
    hour INT NOT NULL DEFAULT 12,
    minute INT NOT NULL DEFAULT 0
);
